version: '3'
services:
  postgres:
    image: postgres:15.2
    restart: always
    container_name: 'footballersapi-postgres'
    env_file: ./containerConfig/psql.env
    ports:
      - "5432:5432"
    volumes:
      - ./containerConfig/footballer.sql:/docker-entrypoint-initdb.d/footballer.sql
      - ./containerConfig/team.sql:/docker-entrypoint-initdb.d/team.sql
      - ./data/psql:/var/lib/postgresql/data
